use std::collections::HashSet;
use std::path::{Path, PathBuf};

use dinopod::compose::{
    build_compose_command, inspect_compose_config, render_override, ComposeFiles, ComposeFs,
    ComposeValidator, ComposeWarning,
};
use dinopod::config::DinopodConfig;
use dinopod::errors::DinopodError;
use dinopod::names::derive_names;

#[derive(Debug, Default)]
struct FakeFs {
    files: HashSet<PathBuf>,
}

impl ComposeFs for FakeFs {
    fn file_exists(&self, path: &Path) -> bool {
        self.files.contains(path)
    }
}

#[test]
fn compose_validator_should_report_missing_compose_file() {
    let validator = ComposeValidator::new(FakeFs::default());

    let error = validator
        .require_compose_file(Path::new("compose.yaml"))
        .expect_err("missing compose file should fail");

    assert!(matches!(error, DinopodError::ComposeFileMissing { .. }));
}

#[test]
fn compose_config_inspection_should_report_missing_app_service() {
    let error = inspect_compose_config(r#"{"services":{"worker":{}}}"#, "app")
        .expect_err("missing app service should fail");

    assert!(matches!(
        error,
        DinopodError::ComposeServiceMissing { service } if service == "app"
    ));
}

#[test]
fn compose_config_inspection_should_warn_about_fixed_host_ports_on_any_service() {
    let inspection = inspect_compose_config(
        r#"{"services":{"app":{},"db":{"ports":[{"target":5432,"published":"5432"}]}}}"#,
        "app",
    )
    .expect("app service should inspect");

    assert_eq!(
        inspection.warnings(),
        [ComposeWarning::FixedHostPort {
            service: "db".to_owned(),
            published: "5432".to_owned(),
        }]
    );
}

#[test]
fn compose_config_inspection_should_warn_about_fixed_host_ports() {
    let inspection = inspect_compose_config(
        r#"{"services":{"app":{"ports":[{"target":3000,"published":"3000"}]}}}"#,
        "app",
    )
    .expect("app service should inspect");

    assert_eq!(
        inspection.warnings(),
        [ComposeWarning::FixedHostPort {
            service: "app".to_owned(),
            published: "3000".to_owned(),
        }]
    );
}

#[test]
fn generated_override_should_attach_only_app_service_to_shared_proxy_network() {
    let config = DinopodConfig::default();
    let names = derive_names("MyApp", "JIRA-123", Path::new("/repo/myapp"), &config)
        .expect("names should derive");

    let override_yaml = render_override(&config, &names);

    assert_eq!(
        override_yaml,
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "services:\n",
            "  app:\n",
            "    networks:\n",
            "      dinopod-proxy:\n",
            "        aliases:\n",
            "          - myapp-jira-123-app\n",
            "networks:\n",
            "  dinopod-proxy:\n",
            "    external: true\n",
            "    name: dinopod-proxy\n",
        )
    );
}

#[test]
fn compose_command_should_include_user_and_dinopod_override_files() {
    let files = ComposeFiles::new(
        Path::new("/repo/myapp/docker-compose.yml"),
        Path::new("/repo/.dinopod-worktrees/myapp-jira-123/.dinopod/compose.override.yml"),
    );

    let command = build_compose_command("myapp-jira-123", &files, ["up", "-d"]);

    assert_eq!(command.program(), "docker");
    assert_eq!(
        command.arguments(),
        [
            "compose",
            "-p",
            "myapp-jira-123",
            "-f",
            "/repo/myapp/docker-compose.yml",
            "-f",
            "/repo/.dinopod-worktrees/myapp-jira-123/.dinopod/compose.override.yml",
            "up",
            "-d",
        ]
    );
}
