use std::collections::HashSet;
use std::path::{Path, PathBuf};

use dinopod::compose::{
    build_compose_command, inspect_compose_config, inspect_compose_config_for_runtime,
    render_infra_override, render_override, validate_infra_host_ports, ComposeFiles, ComposeFs,
    ComposeValidator, ComposeWarning,
};
use dinopod::config::{DinopodConfig, RuntimeMode};
use dinopod::env::PortPlan;
use dinopod::errors::DinopodError;
use dinopod::names::derive_names;

#[derive(Debug, Default)]
struct FakeFs {
    files: HashSet<PathBuf>,
}

impl ComposeFs for FakeFs {
    fn file_exists(&self, path: &Path) -> bool {
        self.files.contains(path)
    }
}

#[test]
fn compose_validator_should_report_missing_compose_file() {
    let validator = ComposeValidator::new(FakeFs::default());

    let error = validator
        .require_compose_file(Path::new("compose.yaml"))
        .expect_err("missing compose file should fail");

    assert!(matches!(error, DinopodError::ComposeFileMissing { .. }));
}

#[test]
fn compose_config_inspection_should_report_missing_app_service() {
    let error = inspect_compose_config(r#"{"services":{"worker":{}}}"#, "app")
        .expect_err("missing app service should fail");

    assert!(matches!(
        error,
        DinopodError::ComposeServiceMissing { service } if service == "app"
    ));
}

#[test]
fn compose_config_inspection_should_warn_about_fixed_host_ports_on_any_service() {
    let inspection = inspect_compose_config(
        r#"{"services":{"app":{},"db":{"ports":[{"target":5432,"published":"5432"}]}}}"#,
        "app",
    )
    .expect("app service should inspect");

    assert_eq!(
        inspection.warnings(),
        [ComposeWarning::FixedHostPort {
            service: "db".to_owned(),
            published: "5432".to_owned(),
        }]
    );
}

#[test]
fn compose_config_inspection_should_warn_about_fixed_host_ports() {
    let inspection = inspect_compose_config(
        r#"{"services":{"app":{"ports":[{"target":3000,"published":"3000"}]}}}"#,
        "app",
    )
    .expect("app service should inspect");

    assert_eq!(
        inspection.warnings(),
        [ComposeWarning::FixedHostPort {
            service: "app".to_owned(),
            published: "3000".to_owned(),
        }]
    );
}

#[test]
fn generated_override_should_attach_only_app_service_to_shared_proxy_network() {
    let config = DinopodConfig::default();
    let names = derive_names("MyApp", "JIRA-123", Path::new("/repo/myapp"), &config)
        .expect("names should derive");

    let override_yaml = render_override(&config, &names, true);

    assert_eq!(
        override_yaml,
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "services:\n",
            "  app:\n",
            "    networks:\n",
            "      default: {}\n",
            "      dinopod-proxy:\n",
            "        aliases:\n",
            "          - myapp-jira-123-app\n",
            "networks:\n",
            "  dinopod-proxy:\n",
            "    external: true\n",
            "    name: dinopod-proxy\n",
        )
    );
}

#[test]
fn compose_command_should_include_user_and_dinopod_override_files() {
    let files = ComposeFiles::new(
        Path::new("/repo/myapp/docker-compose.yml"),
        Path::new("/repo/.dinopod-worktrees/myapp-jira-123/.dinopod/compose.override.yml"),
    );

    let command = build_compose_command("myapp-jira-123", &files, ["up", "-d"]);

    assert_eq!(command.program(), "docker");
    assert_eq!(
        command.arguments(),
        [
            "compose",
            "-p",
            "myapp-jira-123",
            "-f",
            "/repo/myapp/docker-compose.yml",
            "-f",
            "/repo/.dinopod-worktrees/myapp-jira-123/.dinopod/compose.override.yml",
            "up",
            "-d",
        ]
    );
}

#[test]
fn compose_config_inspection_should_detect_explicit_only_networks() {
    let inspection = inspect_compose_config(
        r#"{"services":{"app":{"networks":{"internal":{}}}}}"#,
        "app",
    )
    .expect("app service should inspect");

    assert!(!inspection.attach_implicit_default_network());
}

#[test]
fn compose_config_inspection_should_detect_implicit_default_network() {
    let inspection = inspect_compose_config(r#"{"services":{"app":{}}}"#, "app")
        .expect("app service should inspect");

    assert!(inspection.attach_implicit_default_network());
}

#[test]
fn generated_override_should_omit_default_for_explicit_only_networks() {
    let config = DinopodConfig::default();
    let names = derive_names("MyApp", "JIRA-123", Path::new("/repo/myapp"), &config)
        .expect("names should derive");

    let override_yaml = render_override(&config, &names, false);

    assert_eq!(
        override_yaml,
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "services:\n",
            "  app:\n",
            "    networks:\n",
            "      dinopod-proxy:\n",
            "        aliases:\n",
            "          - myapp-jira-123-app\n",
            "networks:\n",
            "  dinopod-proxy:\n",
            "    external: true\n",
            "    name: dinopod-proxy\n",
        )
    );
}

#[test]
fn native_compose_inspection_should_not_require_app_service() {
    let inspection = inspect_compose_config_for_runtime(
        r#"{"services":{"db":{},"redis":{}}}"#,
        "app",
        RuntimeMode::Native,
    )
    .expect("native infra compose should inspect");

    assert_eq!(inspection.service_names(), ["db", "redis"]);
}

#[test]
fn validate_infra_host_ports_should_reject_user_fixed_ports_before_dinopod_override() {
    let compose_config = serde_json::from_str(
        r#"{"services":{"db":{"ports":[{"target":5432,"published":"5433"}]},"redis":{}}}"#,
    )
    .expect("compose json should parse");
    let port_plan = PortPlan {
        app_host_port: 31000,
        postgres_host_port: Some(54321),
        redis_host_port: Some(63210),
    };

    let error = validate_infra_host_ports(&compose_config, "app", &port_plan)
        .expect_err("user override port should conflict");

    assert!(matches!(
        error,
        DinopodError::InfraHostPortConflict {
            service,
            published
        } if service == "db" && published == 5433
    ));
}

#[test]
fn validate_infra_host_ports_should_accept_dinopod_allocated_ports() {
    let user_compose = serde_json::from_str(
        r#"{"services":{"db":{"ports":[{"target":5432,"published":"5433"}]},"redis":{"ports":[{"target":6379,"published":"6379"}]}}}"#,
    )
    .expect("compose json should parse");
    let port_plan = PortPlan {
        app_host_port: 31000,
        postgres_host_port: Some(54321),
        redis_host_port: Some(63210),
    };
    let infra_override = render_infra_override(
        &user_compose,
        "app",
        &port_plan,
        &["db".to_owned(), "redis".to_owned()],
    );
    let merged = serde_json::from_str::<serde_json::Value>(
        r#"{"services":{"db":{"ports":[{"target":5432,"published":"54321"}]},"redis":{"ports":[{"target":6379,"published":"63210"}]}}}"#,
    )
    .expect("merged compose should parse");
    let _ = infra_override;

    validate_infra_host_ports(&merged, "app", &port_plan)
        .expect("dinopod override ports should validate");
}

#[test]
fn render_infra_override_should_replace_existing_port_mappings() {
    let user_compose = serde_json::from_str(
        r#"{"services":{"db":{"ports":[{"target":5432,"published":"5432"}]},"redis":{}}}"#,
    )
    .expect("compose json should parse");
    let port_plan = PortPlan {
        app_host_port: 31000,
        postgres_host_port: Some(54321),
        redis_host_port: Some(63210),
    };

    let override_yaml = render_infra_override(
        &user_compose,
        "app",
        &port_plan,
        &["db".to_owned(), "redis".to_owned()],
    );

    assert!(override_yaml.contains("ports: !override"));
    assert!(override_yaml.contains("\"54321:5432\""));
    assert!(override_yaml.contains("\"63210:6379\""));
}

#[test]
fn compose_config_inspection_should_warn_about_fixed_container_names() {
    let inspection = inspect_compose_config(
        r#"{"services":{"app":{"container_name":"my-app"},"db":{}}}"#,
        "app",
    )
    .expect("app service should inspect");

    assert_eq!(
        inspection.warnings(),
        [ComposeWarning::FixedContainerName {
            service: "app".to_owned(),
            container_name: "my-app".to_owned(),
        }]
    );
}
