//! Docker Compose validation and Dinopod-owned override generation.

use std::fmt;
use std::path::{Path, PathBuf};

use serde_json::Value;

use crate::cmd::CommandSpec;
use crate::config::DinopodConfig;
use crate::errors::{DinopodError, Result};
use crate::names::EnvironmentNames;

/// Filesystem checks used by Compose validation.
pub trait ComposeFs {
    /// Returns true when `path` is an existing file.
    fn file_exists(&self, path: &Path) -> bool;
}

/// Production filesystem probe for Compose files.
#[derive(Clone, Copy, Debug, Default)]
pub struct StdComposeFs;

impl ComposeFs for StdComposeFs {
    fn file_exists(&self, path: &Path) -> bool {
        path.is_file()
    }
}

/// Validates local Compose inputs before command execution.
#[derive(Debug)]
pub struct ComposeValidator<F> {
    fs: F,
}

impl<F> ComposeValidator<F>
where
    F: ComposeFs,
{
    /// Creates a Compose validator.
    #[must_use]
    pub fn new(fs: F) -> Self {
        Self { fs }
    }

    /// Requires a Compose file to exist.
    ///
    /// # Errors
    ///
    /// Returns [`DinopodError::ComposeFileMissing`] when the file is absent.
    pub fn require_compose_file(&self, path: &Path) -> Result<()> {
        if self.fs.file_exists(path) {
            Ok(())
        } else {
            Err(DinopodError::ComposeFileMissing {
                path: path.to_path_buf(),
            })
        }
    }
}

/// User Compose file plus the Dinopod-owned override file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ComposeFiles {
    user_file: PathBuf,
    override_file: PathBuf,
}

impl ComposeFiles {
    /// Creates a Compose file pair.
    #[must_use]
    pub fn new(user_file: impl Into<PathBuf>, override_file: impl Into<PathBuf>) -> Self {
        Self {
            user_file: user_file.into(),
            override_file: override_file.into(),
        }
    }

    /// Returns the user-owned Compose file.
    #[must_use]
    pub fn user_file(&self) -> &Path {
        &self.user_file
    }

    /// Returns the Dinopod-owned Compose override file.
    #[must_use]
    pub fn override_file(&self) -> &Path {
        &self.override_file
    }
}

/// Non-fatal findings discovered from Compose config inspection.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ComposeWarning {
    /// A service publishes a fixed host port and can collide across projects.
    FixedHostPort {
        /// Service that publishes the port.
        service: String,
        /// Published host port.
        published: String,
    },
}

impl fmt::Display for ComposeWarning {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::FixedHostPort { service, published } => write!(
                formatter,
                "fixed host port published by service `{service}`: {published}"
            ),
        }
    }
}

/// Result of inspecting Docker Compose's canonical JSON model.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ComposeInspection {
    warnings: Vec<ComposeWarning>,
}

impl ComposeInspection {
    /// Returns non-fatal warnings from the inspection.
    #[must_use]
    pub fn warnings(&self) -> &[ComposeWarning] {
        &self.warnings
    }
}

/// Inspects `docker compose config --format json` output for MVP requirements.
///
/// # Errors
///
/// Returns a JSON inspection error when the text is invalid, or
/// [`DinopodError::ComposeServiceMissing`] when `app_service` is absent.
pub fn inspect_compose_config(input: &str, app_service: &str) -> Result<ComposeInspection> {
    let value = serde_json::from_str::<Value>(input)?;
    let Some(service) = value
        .get("services")
        .and_then(Value::as_object)
        .and_then(|services| services.get(app_service))
    else {
        return Err(DinopodError::ComposeServiceMissing {
            service: app_service.to_owned(),
        });
    };

    Ok(ComposeInspection {
        warnings: fixed_host_port_warnings(app_service, service),
    })
}

/// Renders the Dinopod Compose override that attaches the app to the proxy network.
#[must_use]
pub fn render_override(config: &DinopodConfig, names: &EnvironmentNames) -> String {
    format!(
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "services:\n",
            "  {service}:\n",
            "    networks:\n",
            "      {network}:\n",
            "        aliases:\n",
            "          - {alias}\n",
            "networks:\n",
            "  {network}:\n",
            "    external: true\n",
            "    name: {network}\n",
        ),
        service = config.app.service,
        network = config.proxy.network,
        alias = names.network_alias.as_str(),
    )
}

/// Builds a `docker compose` command using the user file and Dinopod override.
#[must_use]
pub fn build_compose_command<I, S>(project_name: &str, files: &ComposeFiles, args: I) -> CommandSpec
where
    I: IntoIterator<Item = S>,
    S: Into<String>,
{
    let mut compose_args = vec![
        "compose".to_owned(),
        "-p".to_owned(),
        project_name.to_owned(),
        "-f".to_owned(),
        path_arg(files.user_file()),
        "-f".to_owned(),
        path_arg(files.override_file()),
    ];
    compose_args.extend(args.into_iter().map(Into::into));
    CommandSpec::new("docker").args(compose_args)
}

fn fixed_host_port_warnings(app_service: &str, service: &Value) -> Vec<ComposeWarning> {
    service
        .get("ports")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|port| {
            port.get("published")
                .and_then(published_port)
                .map(|published| ComposeWarning::FixedHostPort {
                    service: app_service.to_owned(),
                    published,
                })
        })
        .collect()
}

fn published_port(value: &Value) -> Option<String> {
    value
        .as_str()
        .map(ToOwned::to_owned)
        .or_else(|| value.as_u64().map(|port| port.to_string()))
}

fn path_arg(path: &Path) -> String {
    path.display().to_string()
}
