//! Shared Traefik proxy configuration and lifecycle commands.

use std::io;
use std::path::{Path, PathBuf};

use crate::cmd::{CommandOutput, CommandRunner, CommandSpec};
use crate::config::DinopodConfig;
use crate::errors::{DinopodError, Result};

/// Filesystem paths for Dinopod-managed proxy assets.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProxyPaths {
    root: PathBuf,
    compose_file: PathBuf,
    dynamic_config_dir: PathBuf,
}

impl ProxyPaths {
    /// Creates proxy paths under `root`.
    #[must_use]
    pub fn new(root: impl Into<PathBuf>) -> Self {
        let root = root.into();
        let proxy_root = root.join("proxy");
        Self {
            root,
            compose_file: proxy_root.join("compose.yaml"),
            dynamic_config_dir: proxy_root.join("dynamic"),
        }
    }

    /// Returns the Dinopod config root.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Returns the generated proxy Compose file path.
    #[must_use]
    pub fn compose_file(&self) -> &Path {
        &self.compose_file
    }

    /// Returns the Traefik dynamic config directory.
    #[must_use]
    pub fn dynamic_config_dir(&self) -> &Path {
        &self.dynamic_config_dir
    }
}

/// Observed state of the shared proxy container.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProxyStatus {
    /// Proxy is healthy and can be reused.
    Healthy,
    /// Proxy is not running.
    Stopped,
    /// Proxy is running with the wrong image or generated config.
    NeedsRepair,
}

/// Action taken by proxy orchestration.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProxyAction {
    /// Existing proxy was reused.
    Reused,
    /// Proxy startup commands were issued.
    Started,
    /// Proxy repair commands were issued.
    Repaired,
}

/// Coordinates shared proxy lifecycle commands through Docker.
#[derive(Debug)]
pub struct ProxyManager<'a, R> {
    runner: &'a R,
}

impl<'a, R> ProxyManager<'a, R>
where
    R: CommandRunner,
{
    /// Creates a proxy manager.
    #[must_use]
    pub fn new(runner: &'a R) -> Self {
        Self { runner }
    }

    /// Ensures the shared proxy is healthy for the provided status.
    ///
    /// # Errors
    ///
    /// Returns [`DinopodError::DockerCommandFailed`] when Docker rejects a command,
    /// or an I/O error when command execution fails.
    pub fn ensure_proxy(
        &self,
        config: &DinopodConfig,
        paths: &ProxyPaths,
        status: ProxyStatus,
    ) -> Result<ProxyAction> {
        match status {
            ProxyStatus::Healthy => Ok(ProxyAction::Reused),
            ProxyStatus::Stopped => {
                self.start_proxy(config, paths)?;
                Ok(ProxyAction::Started)
            }
            ProxyStatus::NeedsRepair => {
                self.run_docker([
                    "rm".to_owned(),
                    "-f".to_owned(),
                    config.proxy.container_name.clone(),
                ])?;
                self.start_proxy(config, paths)?;
                Ok(ProxyAction::Repaired)
            }
        }
    }

    fn start_proxy(&self, config: &DinopodConfig, paths: &ProxyPaths) -> Result<()> {
        self.ensure_network(&config.proxy.network)?;
        self.run_docker([
            "compose".to_owned(),
            "-p".to_owned(),
            config.proxy.network.clone(),
            "-f".to_owned(),
            path_arg(paths.compose_file()),
            "up".to_owned(),
            "-d".to_owned(),
        ])
    }

    fn ensure_network(&self, network: &str) -> Result<()> {
        let inspect_output = self.run_docker_allow_failure(vec![
            "network".to_owned(),
            "inspect".to_owned(),
            network.to_owned(),
        ])?;

        if inspect_output.success() {
            return Ok(());
        }

        self.run_docker([
            "network".to_owned(),
            "create".to_owned(),
            network.to_owned(),
        ])
    }

    fn run_docker<I, S>(&self, args: I) -> Result<()>
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        let args = args.into_iter().map(Into::into).collect::<Vec<_>>();
        let output = self.run_docker_allow_failure(args.clone())?;
        if output.success() {
            Ok(())
        } else {
            Err(docker_command_failed(args, &output))
        }
    }

    fn run_docker_allow_failure(&self, args: Vec<String>) -> io::Result<CommandOutput> {
        self.runner.run(&CommandSpec::new("docker").args(args))
    }
}

/// Renders the Docker Compose file for the shared Traefik proxy.
#[must_use]
pub fn render_proxy_compose(config: &DinopodConfig, paths: &ProxyPaths) -> String {
    format!(
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "services:\n",
            "  traefik:\n",
            "    image: {image}\n",
            "    container_name: {container}\n",
            "    command:\n",
            "      - --providers.file.directory=/etc/traefik/dynamic\n",
            "      - --providers.file.watch=true\n",
            "      - --entrypoints.web.address=:{port}\n",
            "    ports:\n",
            "      - \"{port}:{port}\"\n",
            "    volumes:\n",
            "      - {dynamic_dir}:/etc/traefik/dynamic:ro\n",
            "    networks:\n",
            "      - {network}\n",
            "networks:\n",
            "  {network}:\n",
            "    external: true\n",
            "    name: {network}\n",
        ),
        image = config.proxy.image,
        container = config.proxy.container_name,
        port = config.proxy.http_port,
        dynamic_dir = paths.dynamic_config_dir().display(),
        network = config.proxy.network,
    )
}

fn docker_command_failed(args: Vec<String>, output: &CommandOutput) -> DinopodError {
    DinopodError::DockerCommandFailed {
        args,
        exit_code: output.exit_code(),
        stderr: output.stderr().to_owned(),
    }
}

fn path_arg(path: &Path) -> String {
    path.display().to_string()
}
