//! Traefik dynamic route generation for Dinopod environments.

use crate::config::DinopodConfig;
use crate::names::EnvironmentNames;

/// Renders a Traefik file-provider route for one Dinopod environment.
#[must_use]
pub fn render_route(config: &DinopodConfig, names: &EnvironmentNames) -> String {
    format!(
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "[http.routers.{router}]\n",
            "rule = \"Host(`{host}`)\"\n",
            "service = \"{service}\"\n",
            "entryPoints = [\"web\"]\n\n",
            "[http.services.{service}.loadBalancer]\n",
            "[[http.services.{service}.loadBalancer.servers]]\n",
            "url = \"http://{service}:{port}\"\n",
        ),
        router = names.project.as_str(),
        host = names.host.as_str(),
        service = names.network_alias.as_str(),
        port = config.app.internal_port,
    )
}
