//! Traefik dynamic route generation for Dinopod environments.

use crate::config::DinopodConfig;
use crate::names::EnvironmentNames;

/// Upstream target for a Dinopod route.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum RouteUpstream {
    /// Route to a Docker network alias inside the shared proxy network.
    ContainerAlias {
        /// Network alias for the app container.
        alias: String,
        /// Container listen port.
        port: u16,
    },
    /// Route to a host process via Traefik's Docker host gateway.
    HostGateway {
        /// Host listen port for the native dev process.
        port: u16,
    },
}

/// Renders a Traefik file-provider route for one Dinopod environment.
#[must_use]
pub fn render_route(config: &DinopodConfig, names: &EnvironmentNames) -> String {
    render_route_with_upstream(
        names,
        &RouteUpstream::ContainerAlias {
            alias: names.network_alias.as_str().to_owned(),
            port: config.app.internal_port,
        },
    )
}

/// Renders a Traefik route using an explicit upstream target.
#[must_use]
pub fn render_route_with_upstream(names: &EnvironmentNames, upstream: &RouteUpstream) -> String {
    let (service_name, url) = match upstream {
        RouteUpstream::ContainerAlias { alias, port } => {
            (alias.clone(), format!("http://{alias}:{port}"))
        }
        RouteUpstream::HostGateway { port } => (
            format!("{}-host", names.project.as_str()),
            format!("http://host.docker.internal:{port}"),
        ),
    };

    format!(
        concat!(
            "# Generated by Dinopod. Do not edit.\n",
            "[http.routers.{router}]\n",
            "rule = \"Host(`{host}`)\"\n",
            "service = \"{service}\"\n",
            "entryPoints = [\"web\"]\n\n",
            "[http.services.{service}.loadBalancer]\n",
            "[[http.services.{service}.loadBalancer.servers]]\n",
            "url = \"{url}\"\n",
        ),
        router = names.project.as_str(),
        host = names.host.as_str(),
        service = service_name,
        url = url,
    )
}
